from __future__ import annotations

import hashlib
import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
EXPORT_MODULE_PATH = REPOSITORY_ROOT / "scripts" / "export_public_release.py"
SECRET_SCAN_MODULE_PATH = REPOSITORY_ROOT / "scripts" / "secret_scan.py"


def load_module(module_name: str, path: Path):
    spec = importlib.util.spec_from_file_location(module_name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


export_public_release = load_module("export_public_release", EXPORT_MODULE_PATH)
secret_scan = load_module("secret_scan", SECRET_SCAN_MODULE_PATH)


class PublicReleaseExportTests(unittest.TestCase):
    def test_select_paths_uses_allowlist_and_denylist(self) -> None:
        config = {
            "include": ["README.md", "src/**", "scripts/**", "docs/**"],
            "exclude": ["docs/grants/**", "scripts/*billing*"],
            "blocked_suffixes": [".pdf"],
            "required_files": ["README.md"],
        }
        paths = [
            "README.md",
            "src/cogniprint/core.py",
            "docs/evidence-dossier.md",
            "docs/grants/private.md",
            "scripts/export_public_release.py",
            "scripts/billing_smoke.py",
            "paper/manuscript.pdf",
        ]

        selected = export_public_release.select_paths(paths, config)

        self.assertEqual(
            selected,
            [
                "README.md",
                "docs/evidence-dossier.md",
                "scripts/export_public_release.py",
                "src/cogniprint/core.py",
            ],
        )

    def test_scan_selected_files_detects_private_administrative_metadata(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            root = Path(temporary_directory)
            relative_path = "docs/private-note.md"
            path = root / relative_path
            path.parent.mkdir(parents=True)
            sensitive_label = "Grant application" + " ID: ABC-123"
            path.write_text(sensitive_label, encoding="utf-8")

            findings = export_public_release.scan_selected_files(root, [relative_path])

        self.assertTrue(any("grant_application_id" in finding for finding in findings))

    def test_plain_software_application_id_is_not_treated_as_grant_metadata(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            root = Path(temporary_directory)
            relative_path = "docs/api.md"
            path = root / relative_path
            path.parent.mkdir(parents=True)
            path.write_text("Application ID: generated by the local API.\n", encoding="utf-8")

            findings = export_public_release.scan_selected_files(root, [relative_path])

        self.assertFalse(any("grant_application_id" in finding for finding in findings))

    def test_scanner_does_not_match_its_own_rule_definitions(self) -> None:
        findings = export_public_release.scan_selected_files(
            REPOSITORY_ROOT,
            ["scripts/export_public_release.py"],
        )

        self.assertEqual(findings, [])

    def test_generated_public_gitignore_protects_local_and_secret_files(self) -> None:
        contents = export_public_release.PUBLIC_GITIGNORE

        self.assertIn(".env\n", contents)
        self.assertIn(".env.*\n", contents)
        self.assertIn("workspace/\n", contents)
        self.assertIn("release_artifacts/\n", contents)
        self.assertIn(".venv/\n", contents)

    def test_exporter_secret_rules_match_main_secret_scanner(self) -> None:
        scanner_rule_names = {rule.name for rule in secret_scan.RULES}
        exporter_rule_names = {name for name, _pattern in export_public_release.SECRET_RULES}

        self.assertEqual(exporter_rule_names, scanner_rule_names)
        self.assertIn("sendgrid_key", exporter_rule_names)

    def test_prepare_destination_rejects_repository_parent(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            parent = Path(temporary_directory)
            root = parent / "repository"
            root.mkdir()

            with self.assertRaises(export_public_release.ReleaseError):
                export_public_release.prepare_destination(root, parent, clean=True)

    def test_validate_required_files_rejects_missing_file(self) -> None:
        config = {
            "include": [],
            "exclude": [],
            "blocked_suffixes": [],
            "required_files": ["README.md"],
        }

        with self.assertRaises(export_public_release.ReleaseError):
            export_public_release.validate_required_files([], config)

    def test_public_safe_workflow_bypasses_global_github_exclude(self) -> None:
        config = {
            "include": ["README.md"],
            "exclude": [".github/**"],
            "blocked_suffixes": [],
            "required_files": ["README.md"],
            "public_safe_workflows": [".github/workflows/public-release-ci.yml"],
        }
        paths = [
            "README.md",
            ".github/workflows/private-admin.yml",
            ".github/workflows/public-release-ci.yml",
        ]

        selected = export_public_release.select_paths(paths, config)
        export_public_release.validate_public_safe_workflows(selected, config)

        self.assertEqual(selected, [".github/workflows/public-release-ci.yml", "README.md"])

    def test_public_safe_workflow_validation_rejects_extra_workflow(self) -> None:
        config = {"public_safe_workflows": [".github/workflows/public-release-ci.yml"]}
        selected = [
            ".github/workflows/private-admin.yml",
            ".github/workflows/public-release-ci.yml",
            "README.md",
        ]

        with self.assertRaises(export_public_release.ReleaseError):
            export_public_release.validate_public_safe_workflows(selected, config)

    def test_manifest_parity_rejects_extra_candidate_file(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            destination = Path(temporary_directory)
            expected = destination / "README.md"
            extra = destination / "extra.md"
            expected.write_text("ok\n", encoding="utf-8")
            extra.write_text("extra\n", encoding="utf-8")
            manifest = {
                "files": [
                    {
                        "path": "README.md",
                        "sha256": hashlib.sha256(expected.read_bytes()).hexdigest(),
                        "size_bytes": expected.stat().st_size,
                    }
                ]
            }

            with self.assertRaises(export_public_release.ReleaseError):
                export_public_release.verify_manifest_parity(destination, manifest)

    def test_manifest_parity_rejects_hash_size_mismatch(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            destination = Path(temporary_directory)
            path = destination / "README.md"
            path.write_text("actual\n", encoding="utf-8")
            manifest = {
                "files": [
                    {
                        "path": "README.md",
                        "sha256": hashlib.sha256(b"expected\n").hexdigest(),
                        "size_bytes": len(b"expected\n"),
                    }
                ]
            }

            with self.assertRaises(export_public_release.ReleaseError):
                export_public_release.verify_manifest_parity(destination, manifest)


if __name__ == "__main__":
    unittest.main()
